In [2]:
import numpy as np


In [3]:
arr = np.array([1,2,3],dtype=np.int8)

In [4]:
arr[1:]
#print(arr.shape)



#print(arr.dtype)

array([2, 3], dtype=int8)

In [5]:
arr = np.array([
    [1,2,3]
    ,[4,5,6]
])
print(arr.shape)
arr

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr[0,:]



array([1, 2, 3])

In [7]:
arr[0,1:]


array([2, 3])

In [8]:
arr[-1,1:]

array([5, 6])

In [9]:
#broadcasting
arr[0] = 12
arr

array([[12, 12, 12],
       [ 4,  5,  6]])

In [10]:
arr[0] = [12, 13 ,14]
arr

array([[12, 13, 14],
       [ 4,  5,  6]])

In [11]:
arr = np.array([
    [10, 20, 30, 40],
    [10, 20, 30, 40]
    ])
arr[0] = [12,13]
arr

ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [ ]:
arr = np.array([256,257], dtype= 'int32')
arr.astype('uint8')

array([0, 1], dtype=uint8)

In [ ]:
arr = np.array([
    [10, 20, 30, 40],
    [10, 20, 30, 40]
    ])

arr > 30

array([[False, False, False,  True],
       [False, False, False,  True]])

In [ ]:

arr[arr > 4] = 50
arr

array([[50, 50, 50, 50],
       [50, 50, 50, 50]])

In [ ]:
arr

array([[10, 20, 30, 40],
       [10, 20, 30, 40]])

In [ ]:
arr[
    arr > 11
    & (arr <=20)
] = 11
arr

array([[11, 11, 11, 11],
       [11, 11, 11, 11]])

In [ ]:
students = np.array(['BOB', 'Alice', 'John'])
notes = np.array([15,18,4])
students[notes >= 10]

                    

array(['BOB', 'Alice'], dtype='<U5')

In [ ]:
ar = np.array([1,2,3])
arr+1

array([[12, 12, 12, 12],
       [12, 12, 12, 12]])

In [ ]:
arr = np.array([1,2,3])
arr2 = np.array([1,1,1])
print(arr+1)
arr+arr2

[2 3 4]


array([2, 3, 4])

In [ ]:
arr.sum()


In [ ]:
arr = np.array([1,2,np.nan])
np.nansum(arr)

np.float64(3.0)

In [ ]:
#Generateur pseudo aleatoire
np.random.seed(1)
np.random.randint(0,10,size=3)


array([5, 8, 9], dtype=int32)

In [ ]:
chars = np.array(['a', 'b', 'c'])
np.random.choice(chars, size = 50)

array(['b', 'a', 'c', 'a', 'a', 'b', 'b', 'c', 'a', 'a', 'b', 'c', 'c',
       'b', 'a', 'c', 'b', 'c', 'b', 'a', 'b', 'b', 'c', 'a', 'a', 'c',
       'c', 'b', 'a', 'c', 'c', 'c', 'a', 'a', 'b', 'b', 'b', 'a', 'a',
       'b', 'b', 'c', 'a', 'b', 'c', 'c', 'a', 'b', 'b', 'a'], dtype='<U1')